import { useCallback, useRef, useState } from 'react';
import { Upload, FileAudio, FileSpreadsheet, FileImage, FileText, FileVideo } from 'lucide-react';
import type { ConvertType } from '@/types';
interface Props { type: ConvertType; onFilesAdd: (files: File[]) => void; accept: string; disabled?: boolean; }
const iconMap: Record<ConvertType, typeof FileAudio> = { audio: FileAudio, video: FileVideo, sheet: FileSpreadsheet, image: FileImage, document: FileText };
const labelMap: Record<ConvertType, string> = { audio: '拖拽音频文件到此处，或点击选择', video: '拖拽视频文件到此处，或点击选择', sheet: '拖拽表格文件到此处，或点击选择', image: '拖拽图片文件到此处，或点击选择', document: '拖拽办公文件到此处，或点击选择' };
const touchLabelMap: Record<ConvertType, string> = { audio: '点击选择音频文件', video: '点击选择视频文件', sheet: '点击选择表格文件', image: '点击选择图片文件', document: '点击选择办公文件' };
const formatMap: Record<ConvertType, string> = { audio: '支持 MP3, FLAC, WAV, AAC, OGG, M4A 等音频格式', video: '支持 MP4, MKV, WEBM, MOV, AVI, FLV, WMV, MPEG, 3GP, TS 等视频格式', sheet: '支持 XLSX, XLS, CSV, ODS, HTML 等格式', image: '支持 PNG, JPG, WEBP, BMP, GIF, SVG, ICO, TIFF 等格式', document: '支持 PDF、Word DOCX、Excel XLSX/XLS/CSV/ODS/HTML、PowerPoint PPTX' };
export default function FileUpload({ type, onFilesAdd, accept, disabled }: Props) {
  const [isDragging, setIsDragging] = useState(false); const inputRef = useRef<HTMLInputElement>(null); const Icon = iconMap[type];
  const isTouch = typeof window !== 'undefined' && ('ontouchstart' in window || navigator.maxTouchPoints > 0);
  const handleDrop = useCallback((e: React.DragEvent) => { e.preventDefault(); setIsDragging(false); if (!disabled && e.dataTransfer.files.length) onFilesAdd(Array.from(e.dataTransfer.files)); }, [disabled, onFilesAdd]);
  return <div onDragEnter={(e) => { e.preventDefault(); setIsDragging(true); }} onDragLeave={(e) => { e.preventDefault(); setIsDragging(false); }} onDragOver={(e) => e.preventDefault()} onDrop={handleDrop} onClick={() => !disabled && inputRef.current?.click()} className={`relative cursor-pointer rounded-xl sm:rounded-2xl border-2 border-dashed p-6 sm:p-10 flex flex-col items-center justify-center gap-2 sm:gap-3 transition-all ${isDragging ? 'border-[#00d4ff] bg-[#00d4ff]/10' : 'border-[var(--border)] bg-[var(--surface)] hover:border-[#00d4ff]/50'} ${disabled ? 'pointer-events-none opacity-40' : ''}`}><div className="w-12 h-12 rounded-xl flex items-center justify-center bg-[var(--surface)]">{isDragging ? <Upload className="w-6 h-6 text-[#00d4ff]" /> : <Icon className="w-6 h-6 text-[#00d4ff]/70" />}</div><div className="text-center"><p className="text-xs sm:text-sm text-[var(--text-strong)] font-medium">{isTouch ? touchLabelMap[type] : labelMap[type]}</p><p className="text-[10px] sm:text-xs text-[var(--text-muted)] mt-1.5">{formatMap[type]}</p></div><input ref={inputRef} type="file" accept={accept} multiple onChange={(e) => { const files = Array.from(e.target.files || []); if (files.length) onFilesAdd(files); e.target.value = ''; }} className="hidden" /></div>;
}
